"""Lazy public exports for application services.

Importing a service submodule must not initialize every service.  In particular,
repositories may depend on small service utilities without importing the
LibraryService dependency graph.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS: dict[str, str] = {'LibraryService': '.library_service',
 'CollectionService': '.collection_service',
 'PlaylistService': '.playlist_service',
 'FavoriteService': '.favorite_service',
 'HistoryService': '.history_service',
 'SmartCollectionService': '.smart_collection_service',
 'SmartRuleEngine': '.smart_rule_engine',
 'FilterEngine': '.filter_engine',
 'SearchEngine': '.search_engine',
 'SortEngine': '.sort_engine',
 'ProviderMusicAnalysisService': '.music_analysis_service',
 'MusicAnalysisService': '.music_analysis_service',
 'AnalyzerProvider': '.music_analysis_service',
 'MockAnalyzerProvider': '.music_analysis_service',
 'DJIntelligenceService': '.dj_intelligence_service',
 'ScoringEngine': '.dj_intelligence_service',
 'CompatibilityResultDTO': '.dj_intelligence_service',
 'SyncService': '.sync_service',
 'SyncAdapter': '.sync_service',
 'MockSyncAdapter': '.sync_service',
 'AssistantFacade': '.assistant_facade',
 'AssistantTool': '.assistant_facade',
 'AssistantResponseDTO': '.assistant_facade',
 'LibraryQueryTool': '.library_tools',
 'PlaylistTool': '.library_tools',
 'CollectionTool': '.library_tools',
 'FavoriteTool': '.library_tools',
 'HistoryTool': '.library_tools',
 'ImportTool': '.library_tools',
 'DJCompatibilityTool': '.library_tools',
 'MusicAnalysisTool': '.library_tools',
 'LibraryQueryInputDTO': '.library_tools',
 'NaturalLibraryQueryDTO': '.library_tools',
 'NaturalLibrarySearchResultDTO': '.library_tools',
 'LibrarySearchItemDTO': '.library_tools',
 'PlaylistToolInputDTO': '.library_tools',
 'CollectionToolInputDTO': '.library_tools',
 'FavoriteToolInputDTO': '.library_tools',
 'HistoryToolInputDTO': '.library_tools',
 'ImportToolInputDTO': '.library_tools',
 'DJCompatibilityInputDTO': '.library_tools',
 'MusicAnalysisInputDTO': '.library_tools',
 'RecommendationTool': '.library_tools',
 'RecommendationToolInputDTO': '.library_tools',
 'MusicAnalysisBatchTool': '.library_tools',
 'MusicAnalysisBatchToolInputDTO': '.library_tools',
 'AssistantContextBuilder': '.assistant_context',
 'AssistantContextDTO': '.assistant_context',
 'ContextProvider': '.assistant_context',
 'AssistantRuntime': '.assistant_runtime',
 'RuntimeRequestDTO': '.assistant_runtime',
 'RuntimeResultDTO': '.assistant_runtime',
 'AssistantProvider': '.assistant_provider',
 'ProviderRequestDTO': '.assistant_provider',
 'ProviderResponseDTO': '.assistant_provider',
 'ProviderCapabilitiesDTO': '.assistant_provider',
 'ProviderConfigDTO': '.assistant_provider',
 'ProviderPolicy': '.assistant_provider',
 'RetryPolicyDTO': '.assistant_provider',
 'ProviderUsageDTO': '.assistant_provider',
 'ProviderErrorDTO': '.assistant_provider',
 'ProviderExecutionResultDTO': '.assistant_provider',
 'ProviderCancellationToken': '.assistant_provider',
 'MockAssistantProvider': '.assistant_provider',
 'ProviderRegistry': '.provider_registry',
 'ProviderSelectionDTO': '.provider_registry',
 'ProviderNotFoundError': '.provider_registry',
 'CredentialProvider': '.provider_credentials',
 'InMemoryCredentialProvider': '.provider_credentials',
 'ProviderCredentialRefDTO': '.provider_credentials',
 'SecretRedactor': '.provider_credentials',
 'CredentialNotFoundError': '.provider_credentials',
 'ProviderTransport': '.provider_transport',
 'TransportRequestDTO': '.provider_transport',
 'TransportResponseDTO': '.provider_transport',
 'TransportErrorDTO': '.provider_transport',
 'MockProviderTransport': '.provider_transport',
 'LocalhostHTTPProviderTransport': '.provider_transport',
 'OpenAIProvider': '.provider_adapters',
 'OllamaProvider': '.provider_adapters',
 'LMStudioProvider': '.provider_adapters',
 'ProviderFactory': '.provider_adapters',
 'ProviderCapabilityResolver': '.provider_adapters',
 'ProviderCapabilityError': '.provider_adapters',
 'OllamaLocalConfigDTO': '.provider_adapters',
 'ToolCallDTO': '.tool_dispatcher',
 'ToolDispatcher': '.tool_dispatcher',
 'ToolRegistry': '.tool_dispatcher',
 'ToolResultDTO': '.tool_dispatcher',
 'ToolSchemaValidator': '.tool_dispatcher',
 'ToolSchemaValidationError': '.tool_dispatcher',
 'PromptBuilder': '.prompt_builder',
 'PromptDTO': '.prompt_builder',
 'ConversationSession': '.conversation_session',
 'ConversationSessionDTO': '.conversation_session',
 'ConversationMessageDTO': '.conversation_session',
 'MessageRole': '.conversation_session',
 'ActionPipeline': '.action_pipeline',
 'ActionProposalDTO': '.action_pipeline',
 'ActionType': '.action_pipeline',
 'ActionValidationDTO': '.action_pipeline',
 'ActionExecutor': '.action_executor',
 'ExecutionRequestDTO': '.action_executor',
 'ExecutionResultDTO': '.action_executor',
 'MockActionExecutor': '.action_executor',
 'ActionExecutionError': '.action_executor',
 'ExecutionAuditEntryDTO': '.action_executor',
 'ExecutionAuditLog': '.action_executor',
 'IdempotencyRegistry': '.action_executor',
 'RollbackResultDTO': '.action_executor',
 'ActionExecutionService': '.action_execution_service',
 'ActionExecutionServiceError': '.action_execution_service',
 'ActionExecutionAuthorizationDTO': '.action_execution_service',
 'ActionExecutionServiceResultDTO': '.action_execution_service',
 'ActionExecutionState': '.action_execution_service',
 'LocalAssistantConfigDTO': '.local_assistant_mvp',
 'LocalAssistantMVP': '.local_assistant_mvp',
 'ToolPlanDTO': '.tool_planner',
 'PlannedToolCallDTO': '.tool_planner',
 'ToolPlanner': '.tool_planner',
 'DeterministicToolPlanner': '.tool_planner',
 'ToolPlanningError': '.tool_planner',
 'ToolPlanExecutionDTO': '.tool_plan_executor',
 'PlannedStepResultDTO': '.tool_plan_executor',
 'ToolPlanExecutor': '.tool_plan_executor',
 'ToolPlanExecutionError': '.tool_plan_executor',
 'ComposedToolResponseDTO': '.tool_result_composer',
 'ToolResultComposer': '.tool_result_composer',
 'ToolResultCompositionError': '.tool_result_composer',
 'RecommendationScoreDTO': '.recommendation_scoring',
 'RecommendationReasonDTO': '.recommendation_scoring',
 'RecommendationScoringEngine': '.recommendation_scoring',
 'RecommendationScoringError': '.recommendation_scoring',
 'RankedRecommendationDTO': '.recommendation_service',
 'RecommendationQueryDTO': '.recommendation_service',
 'RecommendationService': '.recommendation_service',
 'RecommendationServiceError': '.recommendation_service',
 'RecommendationFacade': '.recommendation_facade',
 'RecommendationFacadeQueryDTO': '.recommendation_facade',
 'RecommendationPageDTO': '.recommendation_facade',
 'RecommendationFacadeError': '.recommendation_facade',
 'GlobalRankingService': '.global_ranking_service',
 'GlobalRankingRequestDTO': '.global_ranking_service',
 'GlobalRankingResultDTO': '.global_ranking_service',
 'GlobalRankingStatsDTO': '.global_ranking_service',
 'RankingTrackDTO': '.global_ranking_service',
 'TrackCandidateSourceProtocol': '.global_ranking_service',
 'GlobalRankingError': '.global_ranking_service',
 'InvalidRankingRequestError': '.global_ranking_service',
 'CandidateSourceError': '.global_ranking_service',
 'create_global_recommendation_facade': '.global_ranking_factory',
 'StageTimingDTO': '.optimization_metrics',
 'OperationMetricsDTO': '.optimization_metrics',
 'ExecutionHardeningConfigDTO': '.execution_hardening',
 'ExecutionEventMetricsDTO': '.execution_hardening',
 'ExecutionConcurrencyLimiter': '.execution_hardening',
 'ExecutionHardeningError': '.execution_hardening',
 'HealthSnapshotDTO': '.diagnostics_service',
 'DiagnosticsService': '.diagnostics_service',
 'DiagnosticsError': '.diagnostics_service',
 'SetPlanQueryDTO': '.set_planning',
 'SetPlanTrackDTO': '.set_planning',
 'SetPlanDTO': '.set_planning',
 'SetPlanningPolicyDTO': '.set_planning',
 'SetPlanningEngine': '.set_planning',
 'SetPlanningError': '.set_planning',
 'EnergyPhaseDTO': '.energy_journey',
 'EnergyJourneyDTO': '.energy_journey',
 'SetJourneyPolicyDTO': '.energy_journey',
 'EnergyJourneyPlanner': '.energy_journey',
 'EnergyJourneyError': '.energy_journey',
 'SetBuilderQueryDTO': '.set_builder_facade',
 'SetBuilderResultDTO': '.set_builder_facade',
 'SetBuilderCancelledResultDTO': '.set_builder_facade',
 'SetBuilderFacade': '.set_builder_facade',
 'SetBuilderError': '.set_builder_facade',
 'AudioAnalysisQueryDTO': '.audio_analysis_service',
 'AudioFeaturesDTO': '.audio_analysis_service',
 'AudioAnalysisResultDTO': '.audio_analysis_service',
 'AudioAnalyzerProtocol': '.audio_analysis_service',
 'AudioFeatureExtractorProtocol': '.audio_analysis_service',
 'PCMFeatureExtractor': '.audio_analysis_service',
 'PCMKeyAnalyzer': '.audio_analysis_service',
 'EnergyAnalysisDTO': '.audio_analysis_service',
 'TempoAnalysisDTO': '.audio_analysis_service',
 'ChromaAnalysisDTO': '.audio_analysis_service',
 'KeyAnalysisDTO': '.audio_analysis_service',
 'AudioFileMusicAnalysisService': '.audio_analysis_service',
 'AudioAnalysisError': '.audio_analysis_service',
 'OFFICIAL_AUDIO_FORMAT_ORDER': '.audio_decoder',
 'AudioFormatDTO': '.audio_decoder',
 'DecodedAudioInfoDTO': '.audio_decoder',
 'AudioPCMBlockDTO': '.audio_decoder',
 'AudioDecoderProtocol': '.audio_decoder',
 'AudioDecoderRegistry': '.audio_decoder',
 'WAVPCMDecoder': '.audio_decoder',
 'AIFFPCMDecoder': '.audio_decoder',
 'AudioDecoderError': '.audio_decoder',
 'UnsupportedAudioFormatError': '.audio_decoder',
 'CorruptAudioFileError': '.audio_decoder',
 'FFmpegResolutionDTO': '.ffmpeg_audio_decoder',
 'FFmpegCapabilityDTO': '.ffmpeg_audio_decoder',
 'FFmpegAvailabilityDTO': '.ffmpeg_audio_decoder',
 'FFmpegDecoderConfigDTO': '.ffmpeg_audio_decoder',
 'FFmpegResolver': '.ffmpeg_audio_decoder',
 'FFmpegCapabilityProbe': '.ffmpeg_audio_decoder',
 'FFmpegAudioDecoder': '.ffmpeg_audio_decoder',
 'FFmpegProcessError': '.ffmpeg_audio_decoder',
 'FFmpegRuntimeIntegrityError': '.ffmpeg_audio_decoder',
 'MultiFormatAudioDiagnosticsDTO': '.multi_format_audio_analysis_facade',
 'MultiFormatAudioAnalysisItemDTO': '.multi_format_audio_analysis_facade',
 'MultiFormatAudioAnalysisResultDTO': '.multi_format_audio_analysis_facade',
 'MultiFormatAudioAnalysisFacade': '.multi_format_audio_analysis_facade',
 'MusicAnalysisBatchQueryDTO': '.music_analysis_facade',
 'MusicAnalysisItemResultDTO': '.music_analysis_facade',
 'MusicAnalysisBatchResultDTO': '.music_analysis_facade',
 'MusicAnalysisFacade': '.music_analysis_facade',
 'MusicAnalysisWorker': '.music_analysis_facade',
 'MusicAnalysisBatchError': '.music_analysis_facade',
 'AnalysisMetadataDTO': '.analysis_change_planner',
 'AnalysisChangeDTO': '.analysis_change_planner',
 'AnalysisChangeSetDTO': '.analysis_change_planner',
 'AnalysisWritePolicyDTO': '.analysis_change_planner',
 'AnalysisChangePlanner': '.analysis_change_planner',
 'AnalysisChangePlanningError': '.analysis_change_planner',
 'AnalysisMetadataBackupDTO': '.analysis_persistence_service',
 'AnalysisApplyResultDTO': '.analysis_persistence_service',
 'AnalysisRestoreResultDTO': '.analysis_persistence_service',
 'AnalysisPersistenceService': '.analysis_persistence_service',
 'AnalysisPersistenceError': '.analysis_persistence_service',
 'AnalysisChangePreviewTool': '.analysis_change_tool',
 'TrackMetadataDTO': '.track_metadata_editor',
 'TrackMetadataPatchDTO': '.track_metadata_editor',
 'TrackMetadataChangeDTO': '.track_metadata_editor',
 'BulkMetadataEditQueryDTO': '.track_metadata_editor',
 'BulkMetadataEditResultDTO': '.track_metadata_editor',
 'TrackMetadataEditorService': '.track_metadata_editor',
 'TrackMetadataFacade': '.track_metadata_facade',
 'TrackMetadataPreviewTool': '.track_metadata_tools',
 'TrackMetadataApplyTool': '.track_metadata_tools',
 'ConfirmationManager': '.confirmation_manager',
 'ConfirmationPolicy': '.confirmation_manager',
 'ConfirmationRequestDTO': '.confirmation_manager',
 'ConfirmationResultDTO': '.confirmation_manager',
 'DuplicateFingerprintDTO': '.duplicate_detection_service',
 'DuplicateGroupDTO': '.duplicate_detection_service',
 'DuplicateScanQueryDTO': '.duplicate_detection_service',
 'DuplicateDetectionResultDTO': '.duplicate_detection_service',
 'DuplicateDetectionService': '.duplicate_detection_service',
 'DuplicateProgressDTO': '.duplicate_detection_facade',
 'FingerprintCache': '.duplicate_detection_facade',
 'DuplicateDetectionFacade': '.duplicate_detection_facade',
 'DuplicateDetectionWorker': '.duplicate_detection_facade',
 'DuplicateDetectionTool': '.duplicate_detection_tool',
 'AppSettingsDTO': '.settings_service',
 'GeneralSettingsDTO': '.settings_service',
 'LibrarySettingsDTO': '.settings_service',
 'AnalysisSettingsDTO': '.settings_service',
 'FFmpegSettingsDTO': '.settings_service',
 'AssistantSettingsDTO': '.settings_service',
 'PreviewPlayerSettingsDTO': '.settings_service',
 'LoggingSettingsDTO': '.settings_service',
 'BackupSettingsDTO': '.settings_service',
 'SettingsService': '.settings_service',
 'SettingsError': '.settings_service',
 'SettingsValidationError': '.settings_service',
 'SettingsLoadError': '.settings_service',
 'SettingsMigrationError': '.settings_service',
 'SettingsFutureVersionError': '.settings_service',
 'SettingsPermissionError': '.settings_service',
 'CURRENT_SETTINGS_SCHEMA_VERSION': '.settings_service',
 'AppLoggingService': '.app_logging_service',
 'StructuredLogSanitizer': '.app_logging_service',
 'JSONLinesFormatter': '.app_logging_service',
 'DiagnosticsExportResultDTO': '.app_logging_service',
 'AppLoggingError': '.app_logging_service',
 'LoggingConfigurationError': '.app_logging_service',
 'DiagnosticsExportError': '.app_logging_service',
 'BackupRequestDTO': '.backup_restore_service',
 'BackupResultDTO': '.backup_restore_service',
 'BackupEntryDTO': '.backup_restore_service',
 'BackupManifestDTO': '.backup_restore_service',
 'BackupVerificationDTO': '.backup_restore_service',
 'RestorePlanDTO': '.backup_restore_service',
 'RestoreResultDTO': '.backup_restore_service',
 'RetentionResultDTO': '.backup_restore_service',
 'BackupRestoreService': '.backup_restore_service',
 'BackupError': '.backup_restore_service',
 'BackupCreationError': '.backup_restore_service',
 'BackupVerificationError': '.backup_restore_service',
 'BackupSecurityError': '.backup_restore_service',
 'BackupIncompatibleError': '.backup_restore_service',
 'RestoreError': '.backup_restore_service',
 'RestoreConfirmationError': '.backup_restore_service',
 'RestoreBusyError': '.backup_restore_service',
 'AudioOutputDeviceDTO': '.preview_player',
 'AudioPlaybackBackendProtocol': '.preview_player',
 'PlaybackHistoryPortProtocol': '.preview_player',
 'HistoryPlaybackPortAdapter': '.preview_player',
 'QtMultimediaPlaybackBackend': '.preview_player',
 'DeterministicPlaybackBackend': '.preview_player',
 'PreviewPlayerService': '.preview_player',
 'PreviewTrackDTO': '.preview_player',
 'PreviewPlayerSnapshotDTO': '.preview_player',
 'PreviewPlayerCapabilitiesDTO': '.preview_player',
 'PreviewPlayerState': '.preview_player',
 'PreviewPlayerError': '.preview_player',
 'PlaybackBackendUnavailableError': '.preview_player',
 'TrackNotLoadedError': '.preview_player',
 'TrackFileNotFoundError': '.preview_player',
 'PreviewUnsupportedAudioFormatError': '.preview_player',
 'PlaybackLoadError': '.preview_player',
 'PlaybackOperationError': '.preview_player',
 'PlaybackClosedError': '.preview_player',
 'create_preview_player_service': '.preview_player',
 'DatabaseMigrationCoordinator': '.database_migration_coordinator',
 'DatabaseMigrationResultDTO': '.database_migration_coordinator'}

# Preserve the established public star-import contract without importing the
# referenced modules during package initialization.
__all__ = ['LibraryService',
 'CollectionService',
 'PlaylistService',
 'FavoriteService',
 'HistoryService',
 'SmartCollectionService',
 'SmartRuleEngine',
 'SearchEngine',
 'SortEngine',
 'FilterEngine',
 'MusicAnalysisService',
 'ProviderMusicAnalysisService',
 'AnalyzerProvider',
 'MockAnalyzerProvider',
 'DJIntelligenceService',
 'ScoringEngine',
 'CompatibilityResultDTO',
 'SyncService',
 'SyncAdapter',
 'MockSyncAdapter',
 'AssistantFacade',
 'AssistantTool',
 'AssistantResponseDTO',
 'LibraryQueryTool',
 'PlaylistTool',
 'CollectionTool',
 'FavoriteTool',
 'HistoryTool',
 'ImportTool',
 'DJCompatibilityTool',
 'MusicAnalysisTool',
 'LibraryQueryInputDTO',
 'PlaylistToolInputDTO',
 'CollectionToolInputDTO',
 'FavoriteToolInputDTO',
 'HistoryToolInputDTO',
 'ImportToolInputDTO',
 'DJCompatibilityInputDTO',
 'MusicAnalysisInputDTO',
 'AssistantContextBuilder',
 'AssistantContextDTO',
 'ContextProvider',
 'AssistantRuntime',
 'RuntimeRequestDTO',
 'RuntimeResultDTO',
 'AssistantProvider',
 'ProviderRequestDTO',
 'ProviderResponseDTO',
 'ProviderCapabilitiesDTO',
 'ProviderConfigDTO',
 'ProviderPolicy',
 'RetryPolicyDTO',
 'ProviderUsageDTO',
 'ProviderErrorDTO',
 'ProviderExecutionResultDTO',
 'ProviderCancellationToken',
 'MockAssistantProvider',
 'ProviderRegistry',
 'ProviderSelectionDTO',
 'ProviderNotFoundError',
 'CredentialProvider',
 'InMemoryCredentialProvider',
 'ProviderCredentialRefDTO',
 'SecretRedactor',
 'CredentialNotFoundError',
 'ProviderTransport',
 'TransportRequestDTO',
 'TransportResponseDTO',
 'TransportErrorDTO',
 'MockProviderTransport',
 'LocalhostHTTPProviderTransport',
 'OpenAIProvider',
 'OllamaProvider',
 'LMStudioProvider',
 'ProviderFactory',
 'ProviderCapabilityResolver',
 'ProviderCapabilityError',
 'OllamaLocalConfigDTO',
 'ToolSchemaValidator',
 'ToolSchemaValidationError',
 'ToolCallDTO',
 'ToolDispatcher',
 'ToolRegistry',
 'ToolResultDTO',
 'PromptBuilder',
 'PromptDTO',
 'ConversationSession',
 'ConversationSessionDTO',
 'ConversationMessageDTO',
 'MessageRole',
 'ActionPipeline',
 'ActionProposalDTO',
 'ActionType',
 'ActionValidationDTO',
 'ActionExecutor',
 'ExecutionRequestDTO',
 'ExecutionResultDTO',
 'MockActionExecutor',
 'ActionExecutionError',
 'ExecutionAuditEntryDTO',
 'ExecutionAuditLog',
 'IdempotencyRegistry',
 'RollbackResultDTO',
 'ActionExecutionService',
 'ActionExecutionServiceError',
 'ActionExecutionAuthorizationDTO',
 'ActionExecutionServiceResultDTO',
 'ActionExecutionState',
 'LocalAssistantConfigDTO',
 'LocalAssistantMVP',
 'ConfirmationManager',
 'ConfirmationPolicy',
 'ConfirmationRequestDTO',
 'ConfirmationResultDTO',
 'NaturalLibraryQueryDTO',
 'NaturalLibrarySearchResultDTO',
 'LibrarySearchItemDTO',
 'ToolPlanDTO',
 'PlannedToolCallDTO',
 'ToolPlanner',
 'DeterministicToolPlanner',
 'ToolPlanningError',
 'ToolPlanExecutionDTO',
 'PlannedStepResultDTO',
 'ToolPlanExecutor',
 'ToolPlanExecutionError',
 'ComposedToolResponseDTO',
 'ToolResultComposer',
 'ToolResultCompositionError',
 'RecommendationScoreDTO',
 'RecommendationReasonDTO',
 'RecommendationScoringEngine',
 'RecommendationScoringError',
 'RankedRecommendationDTO',
 'RecommendationQueryDTO',
 'RecommendationService',
 'RecommendationServiceError',
 'RecommendationFacade',
 'RecommendationFacadeQueryDTO',
 'RecommendationPageDTO',
 'RecommendationFacadeError',
 'GlobalRankingService',
 'GlobalRankingRequestDTO',
 'GlobalRankingResultDTO',
 'GlobalRankingStatsDTO',
 'RankingTrackDTO',
 'TrackCandidateSourceProtocol',
 'GlobalRankingError',
 'InvalidRankingRequestError',
 'CandidateSourceError',
 'create_global_recommendation_facade',
 'StageTimingDTO',
 'OperationMetricsDTO',
 'ExecutionHardeningConfigDTO',
 'ExecutionEventMetricsDTO',
 'ExecutionConcurrencyLimiter',
 'ExecutionHardeningError',
 'HealthSnapshotDTO',
 'DiagnosticsService',
 'DiagnosticsError',
 'SetPlanQueryDTO',
 'SetPlanTrackDTO',
 'SetPlanDTO',
 'SetPlanningPolicyDTO',
 'SetPlanningEngine',
 'SetPlanningError',
 'EnergyPhaseDTO',
 'EnergyJourneyDTO',
 'SetJourneyPolicyDTO',
 'EnergyJourneyPlanner',
 'EnergyJourneyError',
 'SetBuilderQueryDTO',
 'SetBuilderResultDTO',
 'SetBuilderCancelledResultDTO',
 'SetBuilderFacade',
 'SetBuilderError',
 'AudioAnalysisQueryDTO',
 'AudioFeaturesDTO',
 'AudioAnalysisResultDTO',
 'AudioAnalyzerProtocol',
 'AudioFileMusicAnalysisService',
 'AudioAnalysisError',
 'AudioFeatureExtractorProtocol',
 'PCMFeatureExtractor',
 'EnergyAnalysisDTO',
 'TempoAnalysisDTO',
 'PCMKeyAnalyzer',
 'ChromaAnalysisDTO',
 'KeyAnalysisDTO',
 'OFFICIAL_AUDIO_FORMAT_ORDER',
 'AudioFormatDTO',
 'DecodedAudioInfoDTO',
 'AudioPCMBlockDTO',
 'AudioDecoderProtocol',
 'AudioDecoderRegistry',
 'WAVPCMDecoder',
 'AIFFPCMDecoder',
 'AudioDecoderError',
 'UnsupportedAudioFormatError',
 'CorruptAudioFileError',
 'FFmpegResolutionDTO',
 'FFmpegCapabilityDTO',
 'FFmpegAvailabilityDTO',
 'FFmpegDecoderConfigDTO',
 'FFmpegResolver',
 'FFmpegCapabilityProbe',
 'FFmpegAudioDecoder',
 'FFmpegProcessError',
 'FFmpegRuntimeIntegrityError',
 'MultiFormatAudioDiagnosticsDTO',
 'MultiFormatAudioAnalysisItemDTO',
 'MultiFormatAudioAnalysisResultDTO',
 'MultiFormatAudioAnalysisFacade',
 'RecommendationTool',
 'RecommendationToolInputDTO',
 'MusicAnalysisBatchTool',
 'MusicAnalysisBatchToolInputDTO',
 'MusicAnalysisBatchQueryDTO',
 'MusicAnalysisItemResultDTO',
 'MusicAnalysisBatchResultDTO',
 'MusicAnalysisFacade',
 'MusicAnalysisWorker',
 'MusicAnalysisBatchError',
 'AnalysisMetadataDTO',
 'AnalysisChangeDTO',
 'AnalysisChangeSetDTO',
 'AnalysisWritePolicyDTO',
 'AnalysisChangePlanner',
 'AnalysisChangePlanningError',
 'AnalysisMetadataBackupDTO',
 'AnalysisApplyResultDTO',
 'AnalysisRestoreResultDTO',
 'AnalysisPersistenceService',
 'AnalysisPersistenceError',
 'AnalysisChangePreviewTool',
 'TrackMetadataDTO',
 'TrackMetadataPatchDTO',
 'TrackMetadataChangeDTO',
 'BulkMetadataEditQueryDTO',
 'BulkMetadataEditResultDTO',
 'TrackMetadataEditorService',
 'TrackMetadataFacade',
 'TrackMetadataPreviewTool',
 'TrackMetadataApplyTool',
 'DuplicateFingerprintDTO',
 'DuplicateGroupDTO',
 'DuplicateScanQueryDTO',
 'DuplicateDetectionResultDTO',
 'DuplicateDetectionService',
 'DuplicateProgressDTO',
 'FingerprintCache',
 'DuplicateDetectionFacade',
 'DuplicateDetectionWorker',
 'DuplicateDetectionTool',
 'AppSettingsDTO',
 'GeneralSettingsDTO',
 'LibrarySettingsDTO',
 'AnalysisSettingsDTO',
 'FFmpegSettingsDTO',
 'AssistantSettingsDTO',
 'PreviewPlayerSettingsDTO',
 'LoggingSettingsDTO',
 'BackupSettingsDTO',
 'SettingsService',
 'SettingsError',
 'SettingsValidationError',
 'SettingsLoadError',
 'SettingsMigrationError',
 'SettingsFutureVersionError',
 'SettingsPermissionError',
 'CURRENT_SETTINGS_SCHEMA_VERSION',
 'AppLoggingService',
 'StructuredLogSanitizer',
 'JSONLinesFormatter',
 'DiagnosticsExportResultDTO',
 'AppLoggingError',
 'LoggingConfigurationError',
 'DiagnosticsExportError',
 'BackupRequestDTO',
 'BackupResultDTO',
 'BackupEntryDTO',
 'BackupManifestDTO',
 'BackupVerificationDTO',
 'RestorePlanDTO',
 'RestoreResultDTO',
 'RetentionResultDTO',
 'BackupRestoreService',
 'BackupError',
 'BackupCreationError',
 'BackupVerificationError',
 'BackupSecurityError',
 'BackupIncompatibleError',
 'RestoreError',
 'RestoreConfirmationError',
 'RestoreBusyError',
 'AudioOutputDeviceDTO',
 'AudioPlaybackBackendProtocol',
 'PlaybackHistoryPortProtocol',
 'HistoryPlaybackPortAdapter',
 'QtMultimediaPlaybackBackend',
 'DeterministicPlaybackBackend',
 'PreviewPlayerService',
 'PreviewTrackDTO',
 'PreviewPlayerSnapshotDTO',
 'PreviewPlayerCapabilitiesDTO',
 'PreviewPlayerState',
 'PreviewPlayerError',
 'PlaybackBackendUnavailableError',
 'TrackNotLoadedError',
 'TrackFileNotFoundError',
 'PreviewUnsupportedAudioFormatError',
 'PlaybackLoadError',
 'PlaybackOperationError',
 'PlaybackClosedError',
 'create_preview_player_service',
 'DatabaseMigrationCoordinator',
 'DatabaseMigrationResultDTO']


def __getattr__(name: str) -> Any:
    """Resolve an established public export only when a caller requests it."""
    try:
        module_name = _EXPORTS[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
